In [2]:
import pandas as pd

In [65]:
df = pd.read_csv("../data/original_dataset.csv")

In [7]:
df.shape
df.head()

,worker_id,survey_year,platform,platform_type,gender,age_years,education_level,city,state,city_tier,...,digital_literacy_score_1_5,smartphone_tier,bank_account_type,upi_app_primary,social_security_coverage,union_or_collective_member,onboarding_document_issue,primary_complaint,injury_last_12_months,injury_compensation_received
0,GW00001,2024,Ola,ride_hailing,Male,25,Graduate,Bhopal,MP,T2,...,4,"Mid-range (₹8,000–20,000)",Cooperative bank,Paytm,Unsure/don't know,Local transport union,NaN,Order volume inconsistent / slow periods,No,NaN
1,GW00002,2026,Zomato,food_delivery,Male,31,No formal education,Pune,Maharashtra,T1,...,1,"Premium (>₹20,000)",Jan Dhan / Basic Savings (PSU),No UPI,No social security coverage,Not aware unions exist,NaN,Fuel cost entirely borne by worker,No,NaN
2,GW00003,2026,Swiggy,food_delivery,Male,31,Class 10 pass,Amritsar,Punjab,T3,...,2,"Budget (<₹8,000)",Regular savings - PSU bank,Google Pay,No social security coverage,Local transport union,NaN,Rating algorithm opaque and unfair,No,NaN
3,GW00004,2024,Porter,logistics,Male,33,Class 10 pass,Delhi,Delhi,T1,...,2,"Mid-range (₹8,000–20,000)",Jan Dhan / Basic Savings (PSU),PhonePe,No social security coverage,Local transport union,Vehicle RC/insurance issue,No weather protection — must work in rain/heat,No,NaN
4,GW00005,2026,Uber,ride_hailing,Male,30,Class 12 pass,Vadodara,Gujarat,T2,...,3,"Budget (<₹8,000)",Regular savings - PSU bank,Google Pay,Only PF (platform-registered),No,Background check delay,No none,No,NaN

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 41 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   worker_id                      50000 non-null  str
 1   survey_year                    50000 non-null  int64
 2   platform                       50000 non-null  str
 3   platform_type                  50000 non-null  str
 4   gender                         50000 non-null  str
 5   age_years                      50000 non-null  int64
 6   education_level                50000 non-null  str
 7   city                           50000 non-null  str
 8   state                          50000 non-null  str
 9   city_tier                      50000 non-null  str
 10  migrant_worker                 50000 non-null  str
 11  origin_state                   50000 non-null  str
 12  years_on_platform              50000 non-null  int64
 13  prior_occupation               50000 non-null  str
 14  reason_joined_platform         50000 non-null  str
 15  covid_related_entry            50000 non-null  str
 16  daily_hours_worked             50000 non-null  float64
 17  orders_or_rides_per_day        50000 non-null  int64
 18  weekly_days_off                50000 non-null  int64
 19  vehicle_type                   49819 non-null  str
 20  monthly_fuel_cost_inr          50000 non-null  int64
 21  monthly_emi_burden_inr         50000 non-null  int64
 22  monthly_gross_income_inr       50000 non-null  int64
 23  monthly_net_income_inr         50000 non-null  int64
 24  festive_peak_income_spike_pct  50000 non-null  float64
 25  dependents_count               50000 non-null  int64
 26  housing_type                   50000 non-null  str
 27  secondary_income_source        11648 non-null  str
 28  platform_rating_out_of_5       50000 non-null  float64
 29  order_cancellation_rate_pct    50000 non-null  float64
 30  preferred_app_language         50000 non-null  str
 31  digital_literacy_score_1_5     50000 non-null  int64
 32  smartphone_tier                50000 non-null  str
 33  bank_account_type              50000 non-null  str
 34  upi_app_primary                50000 non-null  str
 35  social_security_coverage       50000 non-null  str
 36  union_or_collective_member     50000 non-null  str
 37  onboarding_document_issue      27314 non-null  str
 38  primary_complaint              50000 non-null  str
 39  injury_last_12_months          50000 non-null  str
 40  injury_compensation_received   12755 non-null  str
dtypes: float64(4), int64(11), str(26)
memory usage: 15.6 MB

In [11]:
missing = df.isna().sum()

missing[missing > 0].sort_values(ascending = False)

secondary_income_source         38352
injury_compensation_received    37245
onboarding_document_issue       22686
vehicle_type                      181
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["worker_id"].nunique()

50000

In [ ]:
df["secondary_income_source"].value_counts(dropna=False)

secondary_income_source
NaN                           38352
Agricultural land (family)     2356
Teaching/tuition               2352
Spouse income                  2318
Freelance/part-time trade      2315
Rental income                  2307
Name: count, dtype: int64

In [16]:
df["onboarding_document_issue"].value_counts(dropna=False)

onboarding_document_issue
NaN                                    22686
Aadhaar verification delay              8813
Vehicle RC/insurance issue              5992
PAN card required but not available     4937
Driving licence issue                   3970
Background check delay                  2611
App rejected without reason              991
Name: count, dtype: int64

In [17]:
df["injury_compensation_received"].value_counts(dropna=False)

injury_compensation_received
NaN                                 37245
No compensation received             6959
Platform gave one-time payment       2316
Employer covered medical only        1277
Personal insurance covered           1042
Fellow workers helped informally      889
Filed case (pending)                  272
Name: count, dtype: int64

In [18]:
pd.crosstab(
    df["injury_last_12_months"],
    df["injury_compensation_received"],
    dropna=False
)

injury_compensation_received,Employer covered medical only,Fellow workers helped informally,Filed case (pending),No compensation received,Personal insurance covered,Platform gave one-time payment,NaN
injury_last_12_months,,,,,,,
No,0,0,0,0,0,0,37245
Yes,1277,889,272,6959,1042,2316,0

In [19]:
df[df["vehicle_type"].isna()]["platform_type"].value_counts()

platform_type
food_delivery    181
Name: count, dtype: int64

In [20]:
df[df["platform_type"] == "food_delivery"]["vehicle_type"].value_counts(dropna=False)

vehicle_type
Motorcycle (own)         6075
Motorcycle (EMI/loan)    5286
E-bike                   3426
Scooter                  2314
Bicycle                  1586
Car                       191
NaN                       181
Name: count, dtype: int64

In [22]:
df["platform_type"].value_counts()

platform_type
food_delivery     19059
ride_hailing      10947
quick_commerce     7537
bike_taxi          5043
home_services      2942
logistics          2453
hyperlocal         2019
Name: count, dtype: int64

In [23]:
df["platform"].value_counts()

platform
Zomato           10001
Swiggy            9058
Ola               6959
Rapido            5043
Blinkit           4571
Uber              3988
Zepto             2966
Urban Company     2942
Porter            2453
Dunzo             2019
Name: count, dtype: int64

In [24]:
df["gender"].value_counts()

gender
Male      46812
Female     3188
Name: count, dtype: int64

In [25]:
df["city_tier"].value_counts()

city_tier
T2    20974
T1    19171
T3     9855
Name: count, dtype: int64

In [26]:
df["migrant_worker"].value_counts()

migrant_worker
No     30110
Yes    19890
Name: count, dtype: int64

In [27]:
df["age_years"].describe()

count    50000.00000
mean        26.97276
std          6.09509
min         18.00000
25%         22.00000
50%         27.00000
75%         31.00000
max         53.00000
Name: age_years, dtype: float64

In [28]:
df["education_level"].value_counts()

education_level
Class 12 pass          18370
Class 10 pass          13273
ITI/Diploma             6275
Graduate                5348
Class 8-10 dropout      4425
No formal education     1427
Post-Graduate            882
Name: count, dtype: int64

In [29]:
df[[
    "daily_hours_worked",
    "orders_or_rides_per_day",
    "weekly_days_off",
    "monthly_fuel_cost_inr",
    "monthly_emi_burden_inr",
    "monthly_gross_income_inr",
    "monthly_net_income_inr",
    "dependents_count"
]].describe()

,daily_hours_worked,orders_or_rides_per_day,weekly_days_off,monthly_fuel_cost_inr,monthly_emi_burden_inr,monthly_gross_income_inr,monthly_net_income_inr,dependents_count
count,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000
mean,9.183536,15.938620,0.90412,3301.171760,1021.441880,15132.962660,10208.000760,2.26088
std,2.266758,6.532527,0.62560,1611.353578,1575.322815,9449.183969,8537.987602,1.25829
min,4.000000,2.000000,0.00000,0.000000,0.000000,4500.000000,2000.000000,0.00000
25%,7.600000,11.000000,1.00000,2507.000000,0.000000,7827.000000,3182.750000,1.00000
50%,9.200000,16.000000,1.00000,3235.000000,0.000000,12569.000000,7645.000000,2.00000
75%,10.700000,20.000000,1.00000,4071.000000,2511.000000,20233.000000,14815.000000,3.00000
max,17.000000,45.000000,2.00000,10025.000000,6706.000000,62000.000000,59378.000000,5.00000

In [30]:
df.groupby("platform_type")["monthly_net_income_inr"].agg(
    ["count", "mean", "median"]
).sort_values("median", ascending=False)

                count          mean   median
platform_type
home_services    2942  18531.148878  15009.0
ride_hailing    10947  12328.558783   9372.0
logistics        2453  10638.841011   8747.0
food_delivery   19059   9274.594627   7017.0
quick_commerce   7537   8711.636327   7007.0
hyperlocal       2019   7891.357603   5770.0
bike_taxi        5043   7231.178862   5372.0

In [35]:
df[["daily_hours_worked","monthly_net_income_inr"]].corr()

                        daily_hours_worked  monthly_net_income_inr
daily_hours_worked                1.000000                0.016727
monthly_net_income_inr            0.016727                1.000000

In [39]:
df.groupby("platform_type")["daily_hours_worked"].agg(
    ["mean","median"]
)

                    mean  median
platform_type
bike_taxi       9.164644     9.2
food_delivery   9.191783     9.2
home_services   9.192114     9.2
hyperlocal      9.165082     9.1
logistics       9.209865     9.2
quick_commerce  9.178546     9.1
ride_hailing    9.176514     9.2

In [41]:
df["income_retention_pct"] = (df["monthly_net_income_inr"] / df["monthly_gross_income_inr"]) * 100

df["income_retention_pct"].describe()

count    50000.000000
mean        60.451886
std         20.396001
min         12.353305
25%         44.444444
50%         62.562134
75%         76.780184
max         96.008904
Name: income_retention_pct, dtype: float64

In [44]:
df.groupby("platform_type")["income_retention_pct"].agg(["mean", "median"])

                     mean     median
platform_type
bike_taxi       55.342908  55.202980
food_delivery   61.583768  63.465267
home_services   77.450004  82.015418
hyperlocal      61.202485  61.867025
logistics       61.013414  63.732007
quick_commerce  62.757916  64.560050
ride_hailing    54.414630  57.042889

In [46]:
df["vehicle_cost_burden_pct"] = ((df["monthly_fuel_cost_inr"] + df["monthly_emi_burden_inr"]) / df["monthly_gross_income_inr"]) * 100

df["vehicle_cost_burden_pct"].describe()

count    50000.000000
mean        39.902528
std         34.053643
min          0.000000
25%         16.735979
50%         30.895234
75%         54.074663
max        280.177778
Name: vehicle_cost_burden_pct, dtype: float64

In [48]:
df.groupby("platform_type")["vehicle_cost_burden_pct"].agg(["mean", "median"])

                     mean     median
platform_type
bike_taxi       47.832759  38.155487
food_delivery   38.339255  29.974919
home_services   16.880277  11.492117
hyperlocal      39.739385  31.643357
logistics       37.207480  29.756863
quick_commerce  36.927096  28.750560
ride_hailing    47.840769  36.464433

In [53]:
df[[
    "platform_type",
    "monthly_gross_income_inr",
    "monthly_fuel_cost_inr",
    "monthly_emi_burden_inr",
    "vehicle_cost_burden_pct"
    ]].sort_values(
        by="vehicle_cost_burden_pct",
        ascending=False
        ).head(5)

,platform_type,monthly_gross_income_inr,monthly_fuel_cost_inr,monthly_emi_burden_inr,vehicle_cost_burden_pct
43236,ride_hailing,4500,9009,3599,280.177778
2028,ride_hailing,4500,8726,3389,269.222222
27720,ride_hailing,4500,7330,4196,256.133333
7531,ride_hailing,4500,7838,3668,255.688889
39689,ride_hailing,4500,6239,5264,255.622222

In [57]:
df.groupby("migrant_worker")[["monthly_net_income_inr","daily_hours_worked"]].agg(["mean","median"])

               monthly_net_income_inr         daily_hours_worked
                                 mean  median               mean median
migrant_worker
No                       10271.887778  7710.5           9.187074    9.2
Yes                      10111.286928  7539.0           9.178180    9.2

In [59]:
df["social_security_coverage"].value_counts(normalize=True) * 100

social_security_coverage
No social security coverage             55.336
Unsure/don't know                       14.968
Only PF (platform-registered)           11.812
State government welfare scheme only     8.050
Only ESI                                 5.900
Both PF and ESI                          3.934
Name: proportion, dtype: float64

In [60]:
df[df["injury_last_12_months"] == "Yes"]["injury_compensation_received"].value_counts()

injury_compensation_received
No compensation received            6959
Platform gave one-time payment      2316
Employer covered medical only       1277
Personal insurance covered          1042
Fellow workers helped informally     889
Filed case (pending)                 272
Name: count, dtype: int64

In [62]:
df["primary_complaint"].value_counts(normalize=True) * 100
df["primary_complaint"].value_counts()

primary_complaint
No paid sick leave or medical benefits               3703
No weather protection — must work in rain/heat       3668
No none                                              3636
Pay per order too low / no minimum wage guarantee    3614
Surge pricing not passed on to workers               3600
Customer abuse / rating manipulation risk            3576
No proper grievance redressal                        3575
No accident or life insurance                        3559
Rating algorithm opaque and unfair                   3558
App technical glitches reduce earnings               3531
Fear of sudden deactivation without reason           3506
Order volume inconsistent / slow periods             3502
Fuel cost entirely borne by worker                   3500
Long wait times at restaurants/pickup points         3472
Name: count, dtype: int64

In [63]:
df["primary_complaint"].unique()

<StringArray>
[         'Order volume inconsistent / slow periods',
                'Fuel cost entirely borne by worker',
                'Rating algorithm opaque and unfair',
    'No weather protection — must work in rain/heat',
                                           'No none',
            'App technical glitches reduce earnings',
                     'No accident or life insurance',
                     'No proper grievance redressal',
            'Surge pricing not passed on to workers',
         'Customer abuse / rating manipulation risk',
            'No paid sick leave or medical benefits',
        'Fear of sudden deactivation without reason',
      'Long wait times at restaurants/pickup points',
 'Pay per order too low / no minimum wage guarantee']
Length: 14, dtype: str